apiVersion: v1
kind: Service
metadata:
  name: goshimmer-tcp
  labels:
    svc: goshimmer
spec:
  type: LoadBalancer
  ports:
  - name: "gossip"
    port: 14666
    targetPort: 14666
    protocol: TCP
  - name: "fpc"
    port: 10895
    targetPort: 10895
    protocol: TCP
  - name: "http-api"
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: "dashboard"
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: "pprof-profiling"
    port: 6061
    targetPort: 6061
    protocol: TCP
  selector:
    app: goshimmer